In [10]:
import requests
from bs4 import BeautifulSoup
product=[]
import pandas as pd
price=[]
desc=[]
for i in range (2,5):
    url="https://www.flipkart.com/search?q=sports+shoes&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page="+str(i)
    r=requests.get(url)
    soup=BeautifulSoup(r.text,"html.parser")
    box=soup.find("div",class_="DOjaWF gdgoEp")
    names=box.find_all("div",class_="syl9yP")
    for i in names:
        name=i.text
        product.append(name)
    #print(len(product))
    names=box.find_all("div",class_="Nx9bqj")
    for i in names:
        prices=i.text
        price.append(prices)
    #print(len(price))
    df=pd.DataFrame({"Company":product,"prices":price})
    print(df)
    df.to_csv("Downloads/sports.csv")

                  Company  prices
0                HOTSTYLE    ₹269
1                 BOLTAGO    ₹480
2                   asian    ₹873
3   ALASDAIR MENS FASHION    ₹451
4                   asian    ₹824
5                  BRUTON    ₹482
6     World Wear Footwear    ₹323
7                HOTSTYLE    ₹435
8                  CAMPUS  ₹1,255
9                   Birde    ₹499
10                  CLYMB    ₹480
11              richerson    ₹929
12                 action    ₹511
13                 CAMPUS    ₹935
14                 CAMPUS  ₹1,255
15                   DODA    ₹498
16                  CLYMB    ₹480
17               NOBELITE    ₹498
18                  Abros  ₹1,198
19                  Birde    ₹367
20                  CLYMB    ₹480
21               NOBELITE    ₹565
22               GOLDSTAR    ₹499
23        house of common    ₹445
24                  asian    ₹709
25                  asian    ₹773
26                  Birde    ₹367
27                     TR    ₹363
28                 CAMPUS  ₹1,255
29        house of common    ₹397
30                   aadi    ₹476
31                  SUKUN    ₹338
32                  Xtoon    ₹458
33                  Birde    ₹482
34                 CAMPUS    ₹854
35                   DODA    ₹498
36                    JQR    ₹625
37                  Birde    ₹482
38                 ADIDAS  ₹2,372
39                 BRUTON    ₹482
                  Company  prices
0                HOTSTYLE    ₹269
1                 BOLTAGO    ₹480
2                   asian    ₹873
3   ALASDAIR MENS FASHION    ₹451
4                   asian    ₹824
..                    ...     ...
75                  Abros    ₹514
76                  SUKUN    ₹338
77                  Fitze    ₹459
78                  asian  ₹1,570
79               RED TAPE  ₹1,517

[80 rows x 2 columns]
                   Company  prices
0                 HOTSTYLE    ₹269
1                  BOLTAGO    ₹480
2                    asian    ₹873
3    ALASDAIR MENS FASHION    ₹451
4                    asian    ₹824
..                     ...     ...
115               RED TAPE  ₹1,406
116                  SUKUN    ₹338
117                  Fitze    ₹459
118                  Sparx    ₹910
119                     SG  ₹1,544

[120 rows x 2 columns]

In [20]:
import requests
from bs4 import BeautifulSoup
product=[]
import pandas as pd
price=[]
desc=[]
for i in range (2,5):
    url="https://www.flipkart.com/search?q=running+shoes&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&p%5B%5D=facets.brand%255B%255D%3DPUMA&p%5B%5D=facets.brand%255B%255D%3DADIDAS&p%5B%5D=facets.brand%255B%255D%3DNIKE&p%5B%5D=facets.brand%255B%255D%3DCAMPUS&p%5B%5D=facets.brand%255B%255D%3DSkechers&p%5B%5D=facets.brand%255B%255D%3DREEBOK"+str(i)
    r=requests.get(url)
    soup=BeautifulSoup(r.text,"html.parser")
    box=soup.find("div",class_="DOjaWF gdgoEp")
    names=box.find_all("div",class_="syl9yP")
    for i in names:
        name=i.text
        product.append(name)
    #print(len(product))
    names=box.find_all("div",class_="Nx9bqj")
    for i in names:
        prices=i.text
        price.append(prices)
    #print(len(price))
    df=pd.DataFrame({"Company":product,"prices":price})
    print(df)
    df.to_csv("Downloads/running shoes.csv")

   Company  prices
0     PUMA  ₹1,140
1     PUMA  ₹1,140
2   ADIDAS  ₹1,495
3     PUMA  ₹1,140
4     PUMA  ₹1,140
5   CAMPUS  ₹1,255
6     PUMA  ₹1,950
7   CAMPUS    ₹807
8   CAMPUS    ₹985
9     PUMA  ₹1,140
10  CAMPUS  ₹1,226
11    PUMA  ₹1,950
12    PUMA  ₹1,140
13    PUMA  ₹1,140
14    PUMA  ₹1,140
15  CAMPUS    ₹825
16    PUMA  ₹2,481
17    PUMA  ₹1,665
18  CAMPUS    ₹947
19  CAMPUS    ₹853
20    PUMA  ₹2,949
21    PUMA  ₹1,140
22  CAMPUS    ₹985
23  ADIDAS  ₹1,880
24  ADIDAS  ₹1,444
25  CAMPUS    ₹684
26  CAMPUS  ₹1,184
27    PUMA  ₹1,950
28  CAMPUS    ₹854
29  CAMPUS  ₹1,002
30    PUMA  ₹1,140
31    PUMA  ₹1,716
32  CAMPUS  ₹1,088
33  CAMPUS    ₹851
34    PUMA  ₹2,949
35  CAMPUS    ₹868
36    PUMA  ₹2,437
37    PUMA  ₹1,900
38  CAMPUS    ₹439
39  CAMPUS    ₹699
   Company  prices
0     PUMA  ₹1,140
1     PUMA  ₹1,140
2   ADIDAS  ₹1,495
3     PUMA  ₹1,140
4     PUMA  ₹1,140
..     ...     ...
75  CAMPUS    ₹868
76  CAMPUS  ₹1,184
77  CAMPUS  ₹1,165
78  CAMPUS  ₹1,002
79  CAMPUS    ₹999

[80 rows x 2 columns]
    Company  prices
0      PUMA  ₹1,140
1      PUMA  ₹1,140
2    ADIDAS  ₹1,495
3      PUMA  ₹1,140
4      PUMA  ₹1,140
..      ...     ...
115  CAMPUS    ₹868
116    PUMA  ₹1,047
117  CAMPUS  ₹1,184
118  CAMPUS  ₹1,002
119  CAMPUS    ₹999

[120 rows x 2 columns]